// Objective-C API for talking to cfa Go package.
//   gobind -lang=objc cfa
//
// File is generated by gobind. Do not edit.

#ifndef __Clash_H__
#define __Clash_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol ClashPacketFlow;
@class ClashPacketFlow;
@protocol ClashRealTimeLogger;
@class ClashRealTimeLogger;
@protocol ClashTrafficReceiver;
@class ClashTrafficReceiver;

@protocol ClashPacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

@protocol ClashRealTimeLogger <NSObject>
- (void)log:(NSString* _Nullable)level payload:(NSString* _Nullable)payload;
@end

@protocol ClashTrafficReceiver <NSObject>
- (void)receiveTraffic:(int64_t)up down:(int64_t)down;
@end

FOUNDATION_EXPORT BOOL ClashApplyConfig(NSString* _Nullable uuid, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void ClashCloseAllConnections(void);

FOUNDATION_EXPORT void ClashReadPacket(NSData* _Nullable data);

FOUNDATION_EXPORT void ClashSetRealTimeLogger(id<ClashRealTimeLogger> _Nullable l);

FOUNDATION_EXPORT void ClashSetTrafficReceiver(id<ClashTrafficReceiver> _Nullable receive);

FOUNDATION_EXPORT void ClashSetTunnelMode(NSString* _Nullable mode);

FOUNDATION_EXPORT BOOL ClashSetup(id<ClashPacketFlow> _Nullable flow, NSString* _Nullable homeDir, NSString* _Nullable config, NSError* _Nullable* _Nullable error);

@class ClashPacketFlow;

@class ClashRealTimeLogger;

@class ClashTrafficReceiver;

@interface ClashPacketFlow : NSObject <goSeqRefInterface, ClashPacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

@interface ClashRealTimeLogger : NSObject <goSeqRefInterface, ClashRealTimeLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)log:(NSString* _Nullable)level payload:(NSString* _Nullable)payload;
@end

@interface ClashTrafficReceiver : NSObject <goSeqRefInterface, ClashTrafficReceiver> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)receiveTraffic:(int64_t)up down:(int64_t)down;
@end

#endif
